export const LOGIN_THUNK = "LOGIN_THUNK";
export const LOGIN_THUNK_SUCCESS = "LOGIN_THUNK_SUCCESS"
export const LOGOUT_THUNK = "LOGOUT_THUNK";
export const LOGOUT_THUNK_SUCCESS = "LOGOUT_THUNK_SUCCESS";